language: node_js
node_js:
  - "6"
  - "4"

sudo: required

env:
  - CC=clang CXX=clang++ npm_config_clang=1

addons:
  postgresql: "9.5"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_script: NODE_ENV=test lab --coverage-exclude static -r lcov | ./node_modules/.bin/coveralls
